title: Survive the Apocalypse Wiki
description: Official wiki for Survive the Apocalypse

# Any GitHub Pages-supported theme is fine because we override layout.
theme: jekyll-theme-cayman

baseurl: "/survive-the-apocalypse-wiki"
url: "https://xolreyli.github.io"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM